# Generated by Django 3.0.7 on 2020-06-14 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='gender',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
