# Generated by Django 3.0.7 on 2020-06-22 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0002_details_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='name',
        ),
        migrations.AddField(
            model_name='details',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='details',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
