# Generated by Django 3.0.7 on 2020-06-25 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0003_auto_20200622_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='citizen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='details',
            name='elec_dept',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='details',
            name='road_dept',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='details',
            name='water_dep',
            field=models.BooleanField(default=False),
        ),
    ]
