# Generated by Django 3.0.7 on 2020-06-22 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0003_auto_20200622_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='password',
        ),
    ]
